name: Mi-primer-automatizacion
on: 
  push:
      branches: ["*"]
jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v3
      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install
        run: npm ci
      - name: Run Linter
        run: npm run lint